FROM node:12 as node

WORKDIR /app

RUN git clone -b b%%SATALERTAS_TAG%% -o upstream https://github.com/TerraMA2/terrama2-report.git . && \
    npm install

COPY config/environment.prod.ts /app/src/environments/environment.prod.ts
COPY config/environment.ts /app/src/environments/environment.ts

RUN npx ng build --prod --base-href %%TERRAMA2_BASE_PATH%%alerta/ --deploy-url %%TERRAMA2_BASE_PATH%%alerta/

FROM nginx

COPY --from=node /app/dist/terrama2-report/ /usr/share/nginx/html%%TERRAMA2_BASE_PATH%%alerta/
COPY config/nginx.conf /etc/nginx/conf.d/default.conf