FROM %%TERRAMA2_DOCKER_REGISTRY%%/terrama2:%%TERRAMA2_TAG%%

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
                    postgis \
                    # PostgreSQL Client
                    postgresql-client

USER terrama2

EXPOSE 36000

COPY docker-entrypoint.sh /

ENTRYPOINT /docker-entrypoint.sh
